"""add cascade delete photo

Revision ID: dcf2f47b8b17
Revises: a34255a34302
Create Date: 2023-01-02 22:54:55.834162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcf2f47b8b17'
down_revision = 'a34255a34302'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photo', schema=None) as batch_op:
        batch_op.drop_constraint('photo_recipe_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'recipe', ['recipe_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photo', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('photo_recipe_id_fkey', 'recipe', ['recipe_id'], ['id'])

    # ### end Alembic commands ###
